#%RAML 1.0
title: Global Household
version: 2.0.0
protocols:
  - HTTP
baseUri: https://www.hmislynk.com/global-household-api/rest/v3
mediaType: application/json
securedBy: [oauth_2_0]
securitySchemes:
  oauth_2_0: !include security-schemes/oauth_2_0.raml
types:
  global_household: !include global_household.json
  global_household_id: !include global_household_id.json
  global_households: !include global_households.json
  global_households_ids: !include global_households_ids.json
  household_member: !include household_member.json
  household_member_id: !include household_member_id.json
  household_members: !include household_members.json
  household_members_ids: !include household_members_ids.json

/global-households:
  get:
    description: gets a set of global households
    responses:
      '200':
        body:
          application/json:
            example: |
              {
                     "links":[
                        {
                           "rel":"self",
                           "href":"https://wwwh.hmislynk.com/global-household-api/v3/global-households?size=200"
                        }
                     ],
                     "content":[
                        {
                           "globalHouseholdId":"7d968a14-fda9-4bb7-ab89-f6d53ebedc7c",
                           "headOfHouseholdId":"df2f6b58-e29f-4845-bd20-58a5ec0b2529",
                           "dateCreated":"11-13-2017 21:19",
                           "dateUpdated":"11-13-2017 21:19",
                           "dedupClientId":"74520590-3eb3-11e7-85e4-06c37be0e663",
                           "links":[
                              {
                                 "rel":"/hmis-clientapi/rest/v2014/clients/df2f6b58-e29f-4845-bd20-58a5ec0b2529",
                                 "href":"client"
                              }
                           ]
                        }
                     ],
                     "page":{
                        "size":200,
                        "totalElements":1,
                        "totalPages":1,
                        "number":0
                     }
                  }
      '401':
        body:
          application/json:
            example:
              message: ' Unauthorized'
            required: false
      '500':
        body:
          application/json:
            example:
              errorMessage: internal server error
            required: false
    queryParameters:
      inactive:
        required: false
        description: Filter the list of global household by inactive status.
        example: true
        type: boolean
  post:
    description: saves the multiple global household data.
    body:
      application/json:
        example: |
          {
            "dedupClientId": "82bf30b0-9a18-11e7-9920-02fe61f7863e",
            "inactive":false
            }

    responses:
      '200':
        body:
          application/json:
            example: |
                        {
                          "globalHouseholdId":"68f1dcf9-6135-4f9d-92d7-7cc12ee73b7b",
                          "headOfHouseholdId":"08bd3d50-cb87-41ac-8b64-b3dc3853c411",
                          "dateCreated":"11-14-2017 06:52",
                          "dateUpdated":"11-14-2017 06:52",
                          "dedupClientId":"82bf30b0-9a18-11e7-9920-02fe61f7863e"
                          }
      '401':
        body:
          application/json:
            example:
              message: ' Unauthorized'
            required: false
      '500':
        body:
          application/json:
            example:
              message: Resource not found
            required: false
  /{global_household_id}:
    uriParameters:
      global_household_id: {}
    displayName: retreive
    description: 'global household services for get,deactivate and delete.'
    get:
      description: retreives global household  details.
      responses:
        '200':
          body:
            application/json:
              example: |
                {
                   "globalHouseholdId":"68f1dcf9-6135-4f9d-92d7-7cc12ee73b7b",
                   "headOfHouseholdId":"df2f6b58-e29f-4845-bd20-58a5ec0b2529",
                   "dateCreated":"11-14-2017 06:52",
                   "dateUpdated":"11-14-2017 06:52",
                   "dedupClientId":"74520590-3eb3-11e7-85e4-06c37be0e663",
                   "links":[
                      {
                         "rel":"/hmis-clientapi/rest/v2014/clients/df2f6b58-e29f-4845-bd20-58a5ec0b2529",
                         "href":"client"
                      }
                   ]
                }
        '401':
          body:
            application/json:
              example:
                message: ' Unauthorized'
              required: false
        '500':
          body:
            application/json:
              example:
                errorMessage: internal server error
              required: false
    delete:
      description: to delete global household on the basis of uuid
      responses:
        '200':
          description: Global house hold deleted
        '401':
          body:
            application/json:
              example:
                message: ' Unauthorized'
              required: false
        '500':
          body:
            application/json:
              example:
                message: ' Internal Server Error - retry request'
              required: false
    put:
      description: update the multiple global household data.
      body:
        application/json:
          example: |
                  {
                    "dedupClientId": "71b6497c-fe9d-47a5-be47-37a5159c894b",
                    "inactive":true
                  }
      responses:
        '200':
          body:
            application/json:
              example: |
                        {
                          "globalHouseholdId":"68f1dcf9-6135-4f9d-92d7-7cc12ee73b7b",
                          "headOfHouseholdId":"08bd3d50-cb87-41ac-8b64-b3dc3853c411",
                          "dateCreated":"11-14-2017 06:52",
                          "dateUpdated":"11-14-2017 06:52",
                          "dedupClientId":"82bf30b0-9a18-11e7-9920-02fe61f7863e"
                          }
        '401':
          body:
            application/json:
              example:
                message: ' Unauthorized'
              required: false
        '500':
          body:
            application/json:
              example:
                message: Resource not found
              required: false

    /members:
      description: Operations on global household membership
      get:
        responses:
          '200':
            body:
              application/json:
                example: |
                            {
                               "links":[
                                  {
                                     "rel":"self",
                                     "href":"https://www.hmislynk.com/global-household-api/v3/global-households/697386e2-e25d-4674-bdce-c830c96de93e/members"
                                  }
                               ],
                               "content":[
                                  {
                                     "householdMembershipId":"af53eb79-b0ac-4772-8d93-cb4e0cee346d",
                                     "globalClientId":"08bd3d50-cb87-41ac-8b64-b3dc3853c411",
                                     "dateCreated":"11-14-2017 00:11",
                                     "dateUpdated":"11-14-2017 00:11",
                                     "relationshipToHeadOfHousehold":"Testing",
                                     "globalHouseholdId":"697386e2-e25d-4674-bdce-c830c96de93e",
                                     "userId":"8b6c6ef2-87c7-47f0-8874-4cca6f09365c",
                                     "dedupClientId":"82bf30b0-9a18-11e7-9920-02fe61f7863e",
                                     "links":[
                                        {
                                           "rel":"/hmis-clientapi/rest/v2015/clients/08bd3d50-cb87-41ac-8b64-b3dc3853c411",
                                           "href":"client"
                                        }
                                     ]
                                  }
                               ],
                               "page":{
                                  "size":20,
                                  "totalElements":1,
                                  "totalPages":1,
                                  "number":0
                               }
                            }
                required: false
          '401':
            body:
              application/json:
                example:
                  message: ' Unauthorized'
                required: false
          '500':
            body:
              application/json:
                example:
                  message: Resource not found
                required: false
      post:
        responses:
          '200':
            body:
              application/json:
                example: |
                  [
                     {
                        "householdMembershipId":"af53eb79-b0ac-4772-8d93-cb4e0cee346d",
                        "globalClientId":"08bd3d50-cb87-41ac-8b64-b3dc3853c411",
                        "dateCreated":"11-14-2017 00:11",
                        "dateUpdated":"11-14-2017 00:11",
                        "relationshipToHeadOfHousehold":"Mother",
                        "globalHouseholdId":"697386e2-e25d-4674-bdce-c830c96de93e",
                        "userId":"8b6c6ef2-87c7-47f0-8874-4cca6f09365c",
                        "dedupClientId":"82bf30b0-9a18-11e7-9920-02fe61f7863e"
                     }
                  ]
                required: false
          '401':
            body:
              application/json:
                example:
                  message: ' Unauthorized'
                required: false
          '500':
            body:
              application/json:
                example:
                  message: Resource not found
                required: false
        body:
          application/json:
            example: |
                      {
                         "members":[
                            {
                               "relationshipToHeadOfHousehold":"Mother",
                               "globalHouseholdId":"697386e2-e25d-4674-bdce-c830c96de93e",
                               "dedupClientId":"91746d23-3b98-4d43-9724-f1c0f2948784",
                               "inactive":true
                            }
                         ]
                      }
      /{member_id}:
        uriParameters:
          member_id: {}
        get:
          description: get the member record based on member_id.
          responses:
            '200':
              body:
                application/json:
                  example: |
                    {
                       "householdMembershipId":"af53eb79-b0ac-4772-8d93-cb4e0cee346d",
                       "globalClientId":"08bd3d50-cb87-41ac-8b64-b3dc3853c411",
                       "dateCreated":"11-14-2017 00:11",
                       "dateUpdated":"11-14-2017 00:11",
                       "relationshipToHeadOfHousehold":"Mother",
                       "globalHouseholdId":"697386e2-e25d-4674-bdce-c830c96de93e",
                       "userId":"8b6c6ef2-87c7-47f0-8874-4cca6f09365c",
                       "dedupClientId":"82bf30b0-9a18-11e7-9920-02fe61f7863e",
                       "links":[
                          {
                             "rel":"/hmis-clientapi/rest/v2015/clients/08bd3d50-cb87-41ac-8b64-b3dc3853c411",
                             "href":"client"
                          }
                       ]
                    }
                  required: false
            '401':
              body:
                application/json:
                  example:
                    message: ' Unauthorized'
                  required: false
            '500':
              body:
                application/json:
                  example:
                    message: Resource not found
                  required: false
        put:
          description: update the member record.
          body:
            application/json:
              example: |
                          {
                             "relationshipToHeadOfHousehold":"Mother",
                             "dedupClientId":"82bf30b0-9a18-11e7-9920-02fe61f7863e"
                          }
          responses:
            '200':
              body:
                application/json:
                  example:
                    message: member successfully updated.
                  required: false
            '401':
              body:
                application/json:
                  example:
                    message: ' Unauthorized'
                  required: false
            '500':
              body:
                application/json:
                  example:
                    message: Resource not found
                  required: false
        delete:
          description: delete the household member.
          responses:
            '200':
              body:
                application/json:
                  required: false
            '401':
              body:
                application/json:
                  example:
                    message: ' Unauthorized'
                  required: false
            '500':
              body:
                application/json:
                  example:
                    message: Resource not found
                  required: false
