#%RAML 1.0
title: Global Household
version: 1.0.0
protocols:
  - HTTP
baseUri: https://www.hmislynk.com/globalhouseholds/rest
mediaType: application/json
securedBy: [oauth_2_0]
securitySchemes:
  oauth_2_0: !include security-schemes/oauth_2_0.raml
types:
  global_household: !include global_household.json
  global_household_id: !include global_household_id.json
  global_households: !include global_households.json
  global_households_ids: !include global_households_ids.json
  household_member: !include household_member.json
  household_member_id: !include household_member_id.json
  household_members: !include household_members.json
  household_members_ids: !include household_members_ids.json

/global-households:
  get:
    description: gets a set of global households
    responses:
      '200':
        body:
          application/json:
            example: !include global_households_ids_example.json
      '401':
        body:
          application/json:
            example:
              message: ' Unauthorized'
            required: false
      '500':
        body:
          application/json:
            example:
              errorMessage: internal server error
            required: false
    queryParameters:
      inactive:
        required: false
        description: Filter the list of global household by inactive status.
        example: true
        type: boolean
  post:
    description: saves the multiple global household data.
    body:
      application/json:
        type: global_households
        example: !include global_households_example.json
    responses:
      '200':
        body:
          application/json:
            example: !include global_households_ids_example.json
      '401':
        body:
          application/json:
            example:
              message: ' Unauthorized'
            required: false
      '500':
        body:
          application/json:
            example:
              message: Resource not found
            required: false
  put:
    description: update the multiple global household data.
    body:
      application/json:
          type: global_households_ids
          example: !include global_households_ids_example.json
    responses:
      '200':
        body:
          application/json:
            example: !include global_households_ids_example.json
      '401':
        body:
          application/json:
            example:
              message: ' Unauthorized'
            required: false
      '500':
        body:
          application/json:
            example:
              message: Resource not found
            required: false

  /{global_household_id}:
    uriParameters:
      global_household_id: {}
    displayName: retreive
    description: 'global household services for get,deactivate and delete.'
    get:
      description: retreives global household  details.
      responses:
        '200':
          body:
            application/json:
              example: !include global_household_example.json
        '401':
          body:
            application/json:
              example:
                message: ' Unauthorized'
              required: false
        '500':
          body:
            application/json:
              example:
                errorMessage: internal server error
              required: false
    delete:
      description: to delete global household on the basis of uuid
      responses:
        '200':
          body:
            application/json:
              example:
                message: household successfully deleted
              required: false
        '401':
          body:
            application/json:
              example:
                message: ' Unauthorized'
              required: false
        '500':
          body:
            application/json:
              example:
                message: ' Internal Server Error - retry request'
              required: false
    put:
      description: for updating global housing data.
      body:
        application/json:
          type: global_household_id
          example: !include global_household_id_example.json
      responses:
        '200':
          body:
            application/json:
              example:
                message: household successfully updated
              required: false
        '401':
          body:
            application/json:
              example:
                message: ' Unauthorized'
              required: false
        '500':
          body:
            application/json:
              example:
                message: ' Internal Server Error - retry request'
              required: false
    /members:
      description: Operations on global household membership
      get:
        responses:
          '200':
            body:
              application/json:
                example: !include global_households_ids_example.json
                required: false
          '401':
            body:
              application/json:
                example:
                  message: ' Unauthorized'
                required: false
          '500':
            body:
              application/json:
                example:
                  message: Resource not found
                required: false
      post:
        responses:
          '200':
            body:
              application/json:
                example:
                  message: 'address is updated '
                required: false
          '401':
            body:
              application/json:
                example:
                  message: ' Unauthorized'
                required: false
          '500':
            body:
              application/json:
                example:
                  message: Resource not found
                required: false
        body:
          application/json:
            example: !include household_members_ids.json
      put:
        body:
          application/json:
            type: household_members_ids
            example: !include household_members_ids_example.json
        responses:
          '200':
            body:
              application/json:
                example:
                  message: 'members updated '
                required: false
          '401':
            body:
              application/json:
                example:
                  message: ' Unauthorized'
                required: false
          '500':
            body:
              application/json:
                example:
                  message: Resource not found
                required: false
      /{member_id}:
        uriParameters:
          member_id: {}
        get:
          description: get the member record based on member_id.
          responses:
            '200':
              body:
                application/json:
                  example: !include household_member_id_example.json
                  required: false
            '401':
              body:
                application/json:
                  example:
                    message: ' Unauthorized'
                  required: false
            '500':
              body:
                application/json:
                  example:
                    message: Resource not found
                  required: false
        put:
          description: update the member record.
          body:
            application/json:
              type: household_member_id
              example: !include household_member_id_example.json
          responses:
            '200':
              body:
                application/json:
                  example:
                    message: member successfully updated.
                  required: false
            '401':
              body:
                application/json:
                  example:
                    message: ' Unauthorized'
                  required: false
            '500':
              body:
                application/json:
                  example:
                    message: Resource not found
                  required: false
        delete:
          description: delete the household member.
          responses:
            '200':
              body:
                application/json:
                  example:
                    message: member deleted successfully.
                  required: false
            '401':
              body:
                application/json:
                  example:
                    message: ' Unauthorized'
                  required: false
            '500':
              body:
                application/json:
                  example:
                    message: Resource not found
                  required: false
